packages:
  - 'airtunes2/'
  - 'castv2-client/'
  - 'chacha20poly1305/'
  - 'curve25519-js/'
  - 'dns-js/'
  - 'mdns-js/'
  - 'mpris-service/'
  - 'musickit-types/'
  - 'prebuild/'
  - 'prebuild-install/'
  - 'upnp-mediarenderer-client/'
  - 'upnp-device-client/'
  - 'Vinegar/'
